INTERNET_ACCESS: true # Set to true to enable internet access
MAX_SEARCH_RESULTS: 4 # Set the maximum search results for internet access DONT SET TOO HIGH

ALLOW_DM: true # Set to true to allow direct messages
SMART_MENTION: true # Set to true to enable smart mention feature

GPT_MODEL: gpt-3.5-turbo # Model used for chat completion

MAX_HISTORY: 8 # Set the maximum message history

PRESENCES_CHANGE_DELAY: 8 # Please note that the Presences Change Delay is measured in seconds. It is advisable not to set it too low, as doing so may result in your bot being rate-limited by Discord
AI_NSFW_CONTENT_FILTER: false # Enable NSFW AI detector to detect NSFW prompt on Imagine Command

LANGUAGE: ru # Specify the language code (check 'lang' folder for valid codes)

DEFAULT_INSTRUCTION: assist # Specify the instruction prompt to use (check 'instructions' folder for valid prompts)
# To add custom prompts, create a .txt file like 'custom.txt' in `instructions` folder and set INSTRUCTIONS as 'custom'

TRIGGER:
  - chatbot
  - bot nickname
  - bot alias
  - bot name
  - Other bot alias...
# Define the triggers that the bot should always respond to when in message

AUTO_SHARDING: true

DISABLE_PRESENCE: false 
PRESENCES:
  - How can I assist you?
  - Currently in {guild_count} guilds
# List of different presences to be used


BLACKLIST_WORDS:
  - naked
  - loli
  - hentai
  - explicit
  - pornography
  - adult
  - XXX
  - sex
  - erotic
  
# Blacklisted words for /Imagine command this is disabled if you enable AI_NSFW_CONTENT_FILTER
